services:
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '8025:8025'
            - '1025:1025'

    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel

    phpmyadmin:
        image: phpmyadmin
        ports:
        - 8080:80
        environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=db

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8000:80'

    php:
        build: docker/php
        volumes:
            - ./:/var/www/html
